### ISSUE TITLE
Please backport to kibana 4.x

### ISSUE THREAD

**Issue by sabbene** [fermiumlabs/mathlion#11]
sfermiumlabs on freenode kibana requested that i open this issue.

**Comment by ddavidebor** [comment]
working on it in branck backport-4 https://github.com/fermiumlabs/mathlion/tree/backport-4

**Comment by ddavidebor** [comment]
@SimoneTosato got the backport working, check out this [file](https://github.com/fermiumlabs/mathlion/releases/download/beta-1/mathlion-4.x.zip) added to the beta-1 release
