### ISSUE TITLE
Assigning a variable to a split series doesn't work

### ISSUE THREAD

**Issue by sabbene** [fermiumlabs/mathlion#18]
I cannot seem to get a variable to contain a list, when I use split in my .es query.  The behavior I am seeing seems like instead of generating a list, the value of the variable is overwritten with what should have been the last value in the list.  I have attached a screenshot of the issue I am seeing

![image](https://cloud.githubusercontent.com/assets/11637137/19051277/4071d8ba-8967-11e6-8a5b-e39153df2c56.png)

Just noticed that there are two offset='-15m' in the .es query, but the result is the same when it is removed.

**Comment by ddavidebor** [comment]
@SimoneTosato a good occasion to also check all my fixes in the backport branch haven't mess stuff up

**Comment by ddavidebor** [comment]
@sabbene as @SimoneTosato found apparently this problem cannot be solved elegantly in Mathlion.

The problem you found is originated by the fact that you can't assign a variable to a split: 

`.es(split stuff).math(a=source) #does not work
`

but `.es(split stuff).math(source+2)` and similar works correctly.

It would be pretty messy to solve: Imagine the case where `.es(split stuff a)` returns 10 elements and `.es(split stuff b)` returns 12.

If you assign them to two variables,  `math(a+b)`would have no sense.

Also the split values are not singularly identifiable, so what timeseries should go with what?

The first with the first, the second with the second would be the easy answer, but it's a very forced and narrow one.

It can be "solved" by smashing all the split series into single variables (using an average taking advantage of ES for example) and then working only on one main split series

**Comment by ddavidebor** [comment]
A note for @sabbene: TImelion has an (undocumented) variable feature that can help you

**Comment by ddavidebor** [comment]
# Workaround

Simply: do not do assignments. After a split something like `med=median(source)` will not work, but using just  `median(source)` will.

A bit annoying.

PR welcome
