### ISSUE TITLE
Kibana 5.1.2 version

### ISSUE THREAD

**Issue by nejczupan** [fermiumlabs/mathlion#36]
Kindly asking to support for Kibana version 5.1.2

Kind regards,
Nejc

**Comment by ddavidebor** [comment]
Hi, 

The CI is testing with kibana 5.1.2 now https://travis-ci.org/fermiumlabs/mathlion/builds/197084447

Davide

**Comment by ddavidebor** [comment]
@nejczupan could you test https://transfer.sh/srnx4/mathlion-0.2.1-for-kibana-5.1.2.zip and confirm everything is working ?

**Comment by ddavidebor** [comment]
The new release compatible with Kibana 5.1.2 is online:

https://github.com/fermiumlabs/mathlion/releases/tag/v0.2.2

For any problem feel free to open an issue

Davide
