### ISSUE TITLE
Percentiles support

### ISSUE THREAD

**Issue by falzm** [fermiumlabs/mathlion#37]
Hi

This is a follow-up of the [issue opened on the Timelion project](https://github.com/elastic/kibana/issues/8953) requesting support for percentiles: could you please implement it in Mathlion so it would be available in Timelion?

**Comment by ddavidebor** [comment]
Hi,

Does this function do what you need ? http://mathlion.docs.fermiumlabs.com/en/latest/functions/quantileSeq/

Instead of an input array simply use a mathlion variable:

`.es(*).math("quantileSeq(source, 0.5)`

Davide

**Comment by v01t** [comment]
Hi, @ddavidebor,

quantileSeq function returns value (percentile):
` (@1).math('quantileSeq(source, 0.99)')`
will return 99th percentile but as single value for all source and what is expected (based on main issue in Timelion) is a percentiles metric, so I think its not a mathlion or math.js issue.

Regards.

**Comment by ddavidebor** [comment]
Yeah if the percentile metric is already an output of elasticsearch then the problem is in the timelion elasticsearch source.

Regards,
Davide
