### ISSUE TITLE
Kibana 5.2.0 support

### ISSUE THREAD

**Issue by abierbaum** [fermiumlabs/mathlion#38]
Any ETA on a 5.2.0 build?

**Comment by ddavidebor** [comment]
Hi @abierbaum,

The CI is building Mathlion for Kibana 5.2.0.

In about half an hour I should have a prerelease .zip file for you. Feedback and testing welcome.

Davide

**Comment by ddavidebor** [comment]
@abierbaum https://transfer.sh/yBaXe/mathlion-0.2.1-for-kibana-5.2.0.zip

**Comment by abierbaum** [comment]
@ddavidebor Installed and working.  Thanks. :)

**Comment by ddavidebor** [comment]
Released https://github.com/fermiumlabs/mathlion/releases/tag/v0.2.3
