### ISSUE TITLE
Kibana 5.3.0 version

### ISSUE THREAD

**Issue by efwe** [fermiumlabs/mathlion#43]
Hello there,
can I easily build a version for 5.3.0 or do you already know about API changes? 
Thanks in advance
Frank

**Comment by ddavidebor** [comment]
I've read the release not and i see no mention of Timelion.
Can you try @efwe  https://transfer.sh/11I5S2/mathlion-0.2.4_for_kibana-5.3.0.zip ?

Install goes well but I haven't tried it https://travis-ci.org/fermiumlabs/mathlion/jobs/217197232

**Comment by efwe** [comment]
Now that was fast! 
It installed and I will test. 
I  consider this ticket closed.
Thanks

**Comment by SimoneTosato** [comment]
Can we ask you what are you using mathlion for? Knowing what it being used for may help us improve it :smile: we have a Gitter chat for this https://gitter.im/fermiumlabs/mathlion

**Comment by ddavidebor** [comment]
@efwe does everything work correctly?
