### ISSUE TITLE
Re-Compile for Kibana 5.6.0

### ISSUE THREAD

**Issue by mhwest13** [fermiumlabs/mathlion#49]
Hey Gang,

  Just curious if you were going to release this plugin so we could run it against Kibana v5.6.0, since the versions are supposed to stay in lock step in regards to kibana and its plugins.

Cheers,

**Comment by ddavidebor** [comment]
Sure, we just need to change a couple of lines and run the CI again.

(Usually just package.json and travis.yml environmental variables)

Give me a couple of days, I am out of the country. If you're in a hurry
please submit a PR.

Il mar 17 ott 2017, 00:51 Matt West <notifications@github.com> ha scritto:

**Comment by abierbaum** [comment]
Any updates on this?  Really looking forward to running with kibana 5.6.4

**Comment by ddavidebor** [comment]
Very sorry for the delay guys. FIxing it ASAP.
If you've ever in a hurry, i've extended the docs in the README regarding opening a PR when you need to update it, to not have to wait us.

**Comment by ddavidebor** [comment]
Fixed https://github.com/fermiumlabs/mathlion/releases/tag/v0.2.11
