### ISSUE TITLE
Support ES/Kibana 6.x

### ISSUE THREAD

**Issue by external-torx** [fermiumlabs/mathlion#51]
Is this in the plans anywhere? Is it as simple as just installing on an ES6 stack?

**Comment by ddavidebor** [comment]
Hi,
Probably it runs with no issues on ES6. Haven't tried.
Has to be re-released following [this](https://github.com/fermiumlabs/mathlion#how-to-update) instructions.

We're quite full in the coming days.

David

**Comment by ShishkinAR** [comment]
We've got an error during installation mathlion on kibana 6.2.2:
 > Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [mathlion]. Expected [6.2.2]; found [5.6.4]"

So, does mathlion realy support Kibana >= 6.x? If it does - how to install it?

**Comment by pconsigny** [comment]
I can confirm that Mathlion 0.2.11 is working fine with Kibana 6.3.2. Just download mathlion-0.2.11_for_kibana-5.6.4.zip change "version" and "kibanas" in package.json to match your kibana version. 
After that install the plugin with the zip file, instruction there :  https://www.elastic.co/guide/en/kibana/current/install-plugin.html

**Comment by pvnick** [comment]
Works but I had to make a symbolic link on the most recent version (6.6.2):
ln -s /usr/share/kibana/src/legacy/core_plugins/ /usr/share/kibana/src/core_plugins

**Comment by pvnick** [comment]
I do see an error though, e.g. when doing this: .es(*).math("a=source")

I see this error: 

Timelion: Error: in cell #1: Cannot read property '0' of undefined
