### ISSUE TITLE
I see this is support to es kibana 5.6.4 , is support 5.6.8 or high?

### ISSUE THREAD

**Issue by zqc0512** [fermiumlabs/mathlion#52]
I see this is support to es kibana 5.6.4 , is support 5.6.8 or high?

**Comment by ddavidebor** [comment]
Hi,

Almost certainly does. Please follow the procedure here https://github.com/fermiumlabs/mathlion/blob/master/README.md#how-to-request-an-update-for-users

and we will build the new version

Davide
