### ISSUE TITLE
Mathlion behaviour with multiple series

### ISSUE THREAD

**Issue by ddavidebor** [fermiumlabs/mathlion#7]
Mathlion behaviour with multiple series should be tested:

Example `.es(split=user:10)` generate 10 timeseries for the top 10 users. 

If multiple timeseries are passed, the same calculation should be mapped to each and every timeseries. 

The timeseries are meant to represent the same thing, just multiple items of it.

in our case for @fermiumlabs/management applications, we need the ability to apply the same math to every timeseries.

**Comment by SimoneTosato** [comment]
We've just tested and mathlion works perfectly fine with `.es(split=...)`. Closing this issue
